language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
script:
- "./gradlew testDebugUnitTest"
- "./build-apk.sh"