# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.63.0"

default_platform :android

platform :android do
  before_all do
    PROJECT_NAME="sample-ci"   
  end

  # public lanes
  desc "My First Lane"
  lane :test_lane do |options|
    puts "This is a trace test: " + PROJECT_NAME 
    sh 'echo this is a shell test'
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
